FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --legacy-peer-deps

# Copie le reste du code séparément (rechargé par bind mount en local)
COPY . .

ENV NEXT_DISABLE_ESLINT=true

RUN npx prisma generate

EXPOSE 3000
CMD ["npm", "run", "dev"]