# Étape 1 : build
FROM node:24-alpine as build
WORKDIR /app
COPY . .
RUN npm install --legacy-peer-deps
RUN npm run build

# Étape 2 : NGINX
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
