version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cesizen
      POSTGRES_PASSWORD: cesizenpass
      POSTGRES_DB: cesizen
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  api:
    build:
      context: ./api-cesizen
    environment:
      DATABASE_URL: postgres://cesizen:cesizenpass@postgres:5432/cesizen
      NEXT_PUBLIC_API_BASE_URL: http://localhost/api
    expose:
      - "3000"
    depends_on:
      - postgres

  admin:
    build:
      context: ./admin-cesizen
      dockerfile: Dockerfile.prod
    expose:
      - "80"
    depends_on:
      - api

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - admin

volumes:
  postgres_data:
