version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cesizen
      POSTGRES_PASSWORD: cesizenpass
      POSTGRES_DB: cesizen
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  api:
    build:
      context: ./api-cesizen
      dockerfile: Dockerfile.prd
    ports:
      - "4000:3000"
    environment:
      DATABASE_URL: postgres://cesizen:cesizenpass@postgres:5432/cesizen
    depends_on:
      - postgres

  admin:
    build:
      context: ./admin-cesizen
      dockerfile: Dockerfile.prd
      args:
        VITE_API_BASE_ADDRESS: "http://ec2-3-208-244-252.compute-1.amazonaws.com:4000"
    depends_on:
      - api

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prd.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - api
      - admin

volumes:
  postgres_data: