version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cesizen
      POSTGRES_PASSWORD: cesizenpass
      POSTGRES_DB: cesizen
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  api:
    build:
      context: ./api-cesizen
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://cesizen:cesizenpass@postgres:5432/cesizen
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3000
    depends_on:
      - postgres

  admin:
    build:
      context: ./admin-cesizen
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  postgres_data:
